### ISSUE TITLE
Investigate WASM based NetCDF web preview

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/climate-data#3]
Assess options for web based visualization of NetCDF files. Can the Rust NetCDF library be compiled to WASM?

**Comment by fivegrant** [comment]
Ran out of time here but NetCDF in the browser seems to mostly works except for DAP support
#### Takeaways
- `netcdfjs` is the only working browser alternative I found but it doesn't support NetCDF4
- The Rust NetCDF library is just bindings for `netcdf-c` so compiling trivially to WebAssembly doesn't work
- `netcdf-c` can target WebAssembly using Emscripten
  - [Emscripten](https://emscripten.org/) works better out of the box with Autotools as opposed to CMake
  - Building was made easier since NetCDF's dependency [HDF5 already has a port to WASM that includes other dependencies like Zlib](https://github.com/usnistgov/libhdf5-wasm)
- DAP support is difficult since WebAssembly doesn't support HTTP requests which libcurl makes
  - Generally, the solution is to use HTTP with JS code. This doesn't work in the case of `netcdf-c` since it depends on `libcurl`
  - Switching to [Wasix](https://wasix.org/) from Emscripten might alleviate this issue
  
  ----
  
Closing for now since the "investigation" is over. NetCDF-WASM isn't a high priority right now and isn't currently being developed, however, there is a thread to pick up back up on if it becomes important again.

**Comment by fivegrant** [comment]
The tasks that were left were
- [ ] Fix DAP
- [ ] Write a better JS interface around the bindings
